server:
  port: 8011
  servlet:
    context-path: /bankb

spring:
  application:
    # 服务名称
    name: bank-b


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank_b?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root

mybatis-plus:
  type-aliases-package: com.example.bankb.dao
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
    # 是否将自己注册到注册中心
    register-with-eureka: true
    # 是否需要搜索服务信息
    fetch-registry: true
  instance:
    # 使用IP地址注册到注册中心
    prefer-ip-address: true
    #注册中心列表显示的状态参数
    instance-id: ${spring.cloud.client.ip-address}:${server.port}